# Alpaca Configuration for Vega-Aware 0DTE Strategy

# API Credentials (replace with your actual keys)
alpaca:
  paper:
    api_key: "PK1M8P2G3UE4OOI2TFN6"
    secret_key: "VMTSXiwEbj97TEpN0Kreq1jYXae6YCZVvIKxVYv2"
    base_url: "https://paper-api.alpaca.markets"
    data_url: "https://data.alpaca.markets"
  
  live:
    api_key: "YOUR_LIVE_API_KEY"
    secret_key: "YOUR_LIVE_SECRET_KEY"
    base_url: "https://api.alpaca.markets"
    data_url: "https://data.alpaca.markets"

# Strategy Parameters
strategy:
  # Entry times (24-hour format)
  entry_start_time: "15:00"  # 3:00 PM ET
  entry_end_time: "15:30"    # 3:30 PM ET
  
  # Greek parameters
  target_delta: 0.30
  delta_range: 0.05  # Will look for 0.25-0.35 delta
  
  # Vega filters
  min_iv_percentile: 30
  max_vega_ratio: 1.5
  
  # Exit parameters
  profit_target: 0.50  # 50% of premium
  stop_loss: 2.0      # 2x premium
  time_exit_minutes: 15  # Exit 15 min before close
  
  # Position sizing
  position_sizing:
    vega_low: 0.8     # If vega < 0.8: 100% size
    vega_mid: 1.0     # If vega < 1.0: 60% size
    vega_high: 1.5    # If vega < 1.5: 40% size
    
# Risk Management
risk:
  max_daily_loss: 2000
  max_position_size: 10  # Max contracts per leg
  max_account_risk: 0.02  # 2% per trade
  
  # Daily limits
  max_trades_per_day: 5
  stop_after_consecutive_losses: 2
  
# Execution Settings
execution:
  order_type: "limit"
  time_in_force: "day"
  
  # Spread management
  initial_edge: 0.01  # Start $0.01 from mid
  max_chase: 0.03     # Don't chase more than $0.03
  retry_seconds: 30   # Wait before improving price
  
# Monitoring
monitoring:
  log_level: "INFO"
  save_trades: true
  trades_file: "alpaca_trades.csv"
  
  # Alerts
  enable_alerts: true
  alert_on_entry: true
  alert_on_exit: true
  alert_on_profit_target: true
  alert_on_stop_loss: true
  
# Black-Scholes Parameters
greeks:
  risk_free_rate: 0.05  # Current risk-free rate
  calculate_iv: true    # Calculate IV if not provided