# Long Put Strategy with Dynamic Stops and Greeks-Based Exits
# Example configuration showing YAML support in backtester_enhanced.py

name: "Long Put with Dynamic Stops"
description: "Bearish strategy using long puts with volatility-based dynamic stops and Greeks exit triggers"
category: "directional"
version: "1.0"

# Strategy Legs
legs:
  - type: "put"
    direction: "long"
    quantity: 1
    delta_target: -0.40
    delta_tolerance: 0.10

# Entry Rules
entry_rules:
  dte: 30
  dte_tolerance: 5
  dte_range: [20, 45]
  
  target_delta: -0.40
  delta_tolerance: 0.10
  delta_range: [-0.50, -0.30]
  
  # Liquidity Requirements
  volume_min: 100
  open_interest_min: 500
  bid_ask_spread_max_pct: 0.05

# Traditional Exit Rules
exit_rules:
  profit_target_pct: 0.75
  stop_loss_pct: 0.40
  exit_on_dte: 5
  max_hold_days: 30

# Dynamic Volatility Stops
dynamic_stops:
  enabled: true
  
  atr_settings:
    period: 14
    volatility_lookback: 30
    multiplier: 2.0
  
  component_weights:
    atr_weight: 0.4
    vega_weight: 0.35
    theta_weight: 0.25
  
  confidence_threshold: 0.7
  update_frequency: "daily"

# Greeks-Based Exits
greeks_exits:
  enabled: true
  
  delta_threshold_exit:
    enabled: true
    threshold: 0.15
    signal_strength: "moderate"
  
  theta_acceleration_exit:
    enabled: true
    threshold: 2.0
    dte_acceleration_zone: 10
  
  vega_crush_exit:
    enabled: true
    threshold: -25.0
    time_window: 2

# Risk Management
risk_management:
  max_positions: 3
  position_sizing:
    method: "fixed"
    max_position_size_pct: 0.05

# Performance Settings
performance:
  caching:
    enabled: true
    cache_greeks: true
    cache_ttl_seconds: 300

# Logging
logging:
  enabled: true
  export_detailed_logs: false
  export_format: "csv"