# Simple Covered Call Strategy
# Sell calls against stock holdings

name: "Simple Covered Call"
description: "Sell OTM calls for income generation"
category: "income"

# Strategy Configuration
legs:
  - type: call
    direction: short       # Sell calls
    quantity: 1
    delta_target: 0.30     # 30-delta (OTM)

# Entry Rules
entry_rules:
  dte: 30                  # Days to expiration
  delta_target: 0.30       # Target delta (OTM)
  
  # Basic filters
  volume_min: 50           # Minimum volume
  open_interest_min: 200   # Minimum open interest

# Exit Rules  
exit_rules:
  profit_target_pct: 0.50  # Take 50% profit
  stop_loss_pct: 2.00      # Stop at 200% loss
  exit_on_dte: 7           # Exit/roll with 7 days left

# Risk Management
risk_management:
  max_positions: 1         # Max 1 position at a time
  position_sizing: "fixed" # Fixed position size
  max_position_size: 0.10  # 10% of capital

# Execution
execution:
  price_type: "market"     # Use market prices