# Simple Test Strategy for Parquet Data
# Minimal requirements that work with available data columns

name: "Simple Parquet Test"
description: "Basic strategy designed for parquet data structure"
category: "test"

# --- Strategy Legs ---
legs:
  - type: put
    direction: long
    quantity: 1
    delta_target: -0.30
    delta_tolerance: 0.15

# --- Entry Rules ---
entry_rules:
  dte: 30
  dte_tolerance: 10
  dte_range: [20, 45]
  
  target_delta: -0.30
  delta_tolerance: 0.15
  delta_range: [-0.50, -0.15]
  
  # Remove volume/OI requirements since not all data has these
  volume_min: 1              # Very low requirement
  # open_interest_min: 1     # Commented out - not available
  
  # Remove IV rank requirements
  # iv_rank_min: 0
  # iv_rank_max: 100
  
  fallback_enabled: true
  fallback_dte_range: [15, 60]
  fallback_delta_range: [-0.60, -0.10]

# --- Exit Rules ---
exit_rules:
  profit_target_pct: 0.50    # 50% profit target
  stop_loss_pct: 0.50        # 50% stop loss
  exit_on_dte: 10             # Exit at 10 DTE
  max_hold_days: 25

# --- Risk Management ---
risk_management:
  max_positions: 2
  position_sizing: "fixed"
  max_portfolio_exposure: 0.10

# --- Execution Settings ---
execution:
  price_type_entry: "market"
  price_type_exit: "market"
  slippage_model: "empirical"

# --- Price Fallback ---
price_fallback:
  enabled: true
  method: "empirical"
  empirical_settings:
    use_delta_price_map: true
    conservative_bias: true
    include_spread_model: true