# Simple Long Call Strategy
# Basic directional call buying strategy

name: "Simple Long Call"
description: "Buy calls expecting price to go up"
category: "directional"

# Strategy Configuration
legs:
  - type: call
    direction: long        # Buy calls
    quantity: 1
    delta_target: 0.40     # 40-delta calls

# Entry Rules
entry_rules:
  dte: 30                  # Days to expiration
  delta_target: 0.40       # Target delta
  
  # Basic filters
  volume_min: 100          # Minimum volume
  open_interest_min: 500   # Minimum open interest

# Exit Rules  
exit_rules:
  profit_target_pct: 0.50  # Take 50% profit
  stop_loss_pct: 0.50      # Stop at 50% loss
  exit_on_dte: 7           # Exit with 7 days left

# Risk Management
risk_management:
  max_positions: 2         # Max 2 concurrent positions
  position_sizing: "fixed" # Fixed position size
  max_position_size: 0.05  # 5% of capital per trade

# Execution
execution:
  price_type: "market"     # Use market prices