# ORB Strategy Configuration
# Based on backtested results showing 60-min as optimal

# Strategy Selection
active_strategy: orb_60min  # Options: orb_15min, orb_30min, orb_60min

# Strategy Parameters
strategies:
  orb_15min:
    enabled: false
    timeframe_minutes: 15
    win_rate: 0.781  # Historical
    avg_pnl: 35
    
  orb_30min:
    enabled: false
    timeframe_minutes: 30
    win_rate: 0.826  # Historical
    avg_pnl: 31
    
  orb_60min:
    enabled: true
    timeframe_minutes: 60
    win_rate: 0.888  # Historical - BEST
    avg_pnl: 51
    profit_factor: 1.59

# Position Configuration
position:
  spread_width: 15  # $15 wide credit spreads (optimal from article)
  strike_offset: 0.01  # Short strike $0.01 outside OR
  position_size_pct: 0.02  # 2% of account per trade
  max_contracts: 10  # Maximum contracts per trade
  min_contracts: 1  # Minimum contracts

# Entry Filters
filters:
  min_range_pct: 0.002  # 0.2% minimum OR width
  max_range_pct: 0.02  # 2% maximum (avoid gap days)
  min_volume: 1000000  # Minimum volume in OR
  volume_surge: 1.5  # Volume must be 1.5x average for breakout
  confirmation_bars: 2  # Bars needed to confirm breakout
  
# Entry Windows
timing:
  or_start: "09:30"  # Opening range start
  or_end_15min: "09:45"
  or_end_30min: "10:00"
  or_end_60min: "10:30"
  entry_cutoff: "15:30"  # No new entries after
  market_close: "16:00"
  
# Exit Rules
exits:
  profit_target_pct: 0.8  # Take profit at 80% of max profit
  stop_loss_multiplier: 2.0  # Stop at 2x credit received
  time_exit: "15:59"  # Force exit 1 minute before close
  trail_profit: false  # Trail stops after profit target
  
# Risk Management
risk:
  max_daily_trades: 1  # Only first breakout per day
  max_daily_loss: 5000  # Stop trading if daily loss exceeds
  max_weekly_loss: 10000  # Weekly loss limit
  max_positions: 1  # Maximum concurrent positions
  
# Greeks Limits (for entry)
greeks:
  max_delta: 0.35  # Maximum delta for short strike
  max_vega_ratio: 0.02  # Maximum vega/premium ratio
  min_theta: 10  # Minimum theta (per contract)
  
# Execution Settings
execution:
  order_type: limit  # limit or market
  limit_offset: 0.02  # Limit order offset from mid
  smart_routing: true  # Use smart order routing
  leg_separately: true  # Leg into spreads
  max_slippage: 0.05  # Maximum acceptable slippage
  
# Backtesting Settings
backtest:
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  initial_capital: 100000
  commission_per_contract: 0.65
  slippage_per_contract: 0.02
  
# Live Trading Settings
live:
  paper_trade: true  # Start with paper trading
  api: alpaca  # Trading platform
  data_source: alpaca  # Data provider
  
# Monitoring & Alerts
monitoring:
  log_trades: true
  save_to_database: true
  send_alerts: false
  alert_email: ""
  performance_report_frequency: daily  # daily, weekly, monthly
  
# Performance Targets (based on backtests)
targets:
  daily_profit_target: 200
  weekly_profit_target: 1000
  monthly_profit_target: 4000
  expected_win_rate: 0.85
  expected_profit_factor: 1.5