category: test
description: Integration test strategy
dynamic_stops:
  atr_settings:
    period: 14
    volatility_lookback: 30
  component_weights:
    atr_weight: 0.4
    theta_weight: 0.25
    vega_weight: 0.35
  enabled: true
entry_rules:
  delta_tolerance: 0.1
  dte: 30
  dte_tolerance: 5
  target_delta: -0.4
  volume_min: 100
exit_rules:
  exit_on_dte: 5
  profit_target_pct: 0.75
  stop_loss_pct: 0.4
greeks_exits:
  delta_threshold_exit:
    enabled: true
    threshold: 0.15
  enabled: true
legs:
- delta_target: -0.4
  delta_tolerance: 0.1
  direction: long
  quantity: 1
  type: put
name: Test Strategy
version: '1.0'
