# ZEBRA Call Strategy with 10% OTM Put Protection
# Zero Extrinsic Back Ratio with disaster hedge
# Buy 2 ITM Calls + Sell 1 OTM Call + Buy 1 Protective Put

name: "ZEBRA Call Spread with 10% Put Hedge"
description: "ZEBRA call spread with protective put 10% below spot price (disaster protection)"
strategy_type: "custom_spread"
category: "directional_hedged"

# Strategy Parameters
parameters:
  initial_capital: 100000   # Starting capital
  position_size: 0.10       # 10% of capital per trade
  max_positions: 3          # Max concurrent positions
  max_hold_days: 45         # Max days to hold position
  entry_frequency: 30       # Days between entries (monthly)

# Multi-Leg Configuration
legs:
  # Leg 1: Buy 2 ITM Calls
  - name: "long_itm_calls"
    type: call
    direction: long
    quantity: 2
    delta_target: 0.55      # 55 delta (ITM)
    
  # Leg 2: Sell 1 OTM Call
  - name: "short_otm_call"
    type: call
    direction: short
    quantity: 1
    delta_target: 0.30      # 30 delta (OTM)
    
  # Leg 3: Buy 1 Protective Put (10% OTM)
  - name: "protective_put"
    type: put
    direction: long
    quantity: 1
    strike_offset_pct: -0.10  # 10% below spot price

# Option Selection Configuration
option_selection:
  method: "multi_leg"       # Multi-leg selection
  
  # ITM Calls Selection
  leg_1_long_calls:
    delta_criteria:
      target: 0.55          # Target 55 delta
      tolerance: 0.05       # Accept 50-60 delta
      
    dte_criteria:
      target: 45            # Target 45 DTE
      minimum: 35           # Min 35 days
      maximum: 60           # Max 60 days
      
    liquidity_criteria:
      min_volume: 100       # Minimum daily volume
      max_spread_pct: 0.10  # Maximum 10% bid-ask spread
  
  # OTM Call Selection
  leg_2_short_call:
    delta_criteria:
      target: 0.30          # Target 30 delta
      tolerance: 0.05       # Accept 25-35 delta
      
    dte_criteria:
      match_leg_1: true     # Same expiration as leg 1
      
    liquidity_criteria:
      min_volume: 100       # Minimum daily volume
      max_spread_pct: 0.10  # Maximum 10% bid-ask spread
      
  # Protective Put Selection
  leg_3_protective_put:
    strike_criteria:
      method: "percentage_otm"
      offset_pct: -0.10     # 10% below current price
      round_to: 1.0         # Round to nearest dollar strike
      
    dte_criteria:
      match_leg_1: true     # Same expiration as calls
      
    liquidity_criteria:
      min_volume: 25        # Very low volume OK for disaster hedge
      max_spread_pct: 0.20  # Allow wider spread for deep OTM

# Entry Rules  
entry_rules:
  market_conditions:
    min_iv_rank: 0          # No IV requirement
    max_iv_rank: 100        # No IV requirement
    
  position_criteria:
    net_delta_target: 0.79  # Net delta ~79 (minimal put delta impact)
    max_net_debit: 0.10     # Max 10% of capital per spread
    min_risk_reward: 3.0    # Min 3:1 reward/risk ratio (cheap hedge)
    
  timing:
    avoid_earnings: true    # Skip entry week before earnings
    avoid_fomc: true        # Skip entry day before FOMC

# Exit Rules
exit_rules:
  - condition: "profit_target"
    target_percent: 50      # Exit at 50% profit (higher with cheap hedge)
    
  - condition: "stop_loss"
    stop_percent: -30       # Exit at 30% loss (wider with disaster hedge)
    
  - condition: "time_stop"
    days_before_expiry: 7   # Exit 7 days before expiration
    
  - condition: "delta_threshold"
    short_call_delta: 0.70  # Exit if short call reaches 70 delta
    
  - condition: "protective_put_itm"
    put_delta: -0.70       # Exit if put goes ITM (major market drop)

# Risk Management
risk_management:
  max_positions: 3          # Max 3 concurrent ZEBRA spreads
  position_sizing: "fixed"  # Fixed position size
  max_position_size: 0.10   # 10% of capital per spread
  
  # Greeks limits (position level)
  max_position_delta: 90    # Higher delta with minimal hedge
  max_position_gamma: -48   # Higher gamma risk
  max_position_theta: -90   # Higher theta decay
  max_position_vega: -190   # Higher vega exposure
  
  # Tail risk protection
  max_portfolio_var_95: 0.07  # Max 7% VaR at 95% confidence
  max_portfolio_cvar_95: 0.10 # Max 10% CVaR at 95% confidence
  
  # Disaster protection metrics
  max_10pct_drop_loss: 0.15   # Max 15% loss if market drops 10%
  max_20pct_drop_loss: 0.25   # Max 25% loss if market drops 20%

# Execution
execution:
  price_type: "mid"         # Use mid prices
  slippage_ticks: 1         # 1 tick slippage per leg
  commission_per_contract: 0.65  # Commission per contract

# Reporting
reporting:
  track_legs_separately: true      # Track each leg P&L
  calculate_net_greeks: true        # Calculate spread Greeks
  log_entry_reason: true            # Log why position entered
  log_exit_reason: true             # Log why position exited
  track_hedge_effectiveness: true  # Track put hedge performance
  separate_hedge_pnl: true         # Report hedge P&L separately
  hedge_cost_analysis: true        # Analyze cost vs protection benefit
  tail_event_analysis: true        # Track performance during >5% drops